# generated by datamodel-codegen:
#   filename:  openapi.json

from __future__ import annotations

from pydantic import BaseModel, Field


class ProcessResponse(BaseModel):
    processed: bool = Field(..., title="Processed")
    job_id: str | None = Field(None, title="Job Id")
    source: str | None = Field(None, title="Source")
    status: str | None = Field(None, title="Status")
    message: str | None = Field(None, title="Message")
